---
# tasks file for wordpress
- name: Wordpres ECS | task definition
  ecs_taskdefinition:
    containers:
    - name: wordpress-app
      cpu: 10
      essential: true 
      image: "wordpress"
      memory: 300
      mountPoints:
      - containerPath: "/var/www/html/wp-content"
      portMappings:
      - containerPort: 80
        hostPort: 80
    state: present
    region: "us-east-1"
  register: task_output

- name: Wordpress ECS | service definition
  ecs_service:
      name: wp-service
      cluster: wp-ecs
      task_definition: worpdress-app
      desired_count: 2
      region: "us-east-1"
      deployment_configuration:
        minimum_healthy_percent: 75
        maximum_percent: 150
      state: present 